spring.application.name=back_AdminZonet

# Configuración de la Base de Datos (Railway)
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:32016/railway
spring.datasource.username=root
spring.datasource.password=NrjoTWWsOiuRkTOqkexxpNxVUeAcTiXH
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor para el Admin
server.port=8081